"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { usePortalRouter } from "../portal-navigation";
import { PushNotificationsCard } from "./PushNotificationsCard";

type Item = Record<string, string | number | null>;
type CitizenData = { profile: Item; products: Item[]; requests: Item[]; needs: Item[]; specialties: Item[]; schedules: Item[]; interests: Item[]; notifications: Item[]; messages: Item[]; slots: Item[]; privacyRequests: Item[] };
const labels: Record<string,string> = { received:"Recebida", approved:"Aprovada", ready_for_pickup:"Pronta para retirar", delivery_scheduled:"Entrega agendada", completed:"Concluída", rejected:"Não aprovada", planned:"Prevista", confirmed:"Confirmada", active:"Registrada", notified:"Avisado" };
const nav = [{id:"inicio",icon:"⌂",label:"Início"},{id:"medicamentos",icon:"Rx",label:"Medicamentos"},{id:"especialistas",icon:"♡",label:"Especialistas"},{id:"mensagens",icon:"◌",label:"Mensagens"},{id:"privacidade",icon:"i",label:"Privacidade"}];
function fmtDate(value: unknown, time=true) { if (!value) return "—"; return new Date(String(value)).toLocaleString("pt-BR", time ? {dateStyle:"short",timeStyle:"short"} : {dateStyle:"long"}); }

export function CitizenPortal() {
  const [data,setData]=useState<CitizenData|null>(null); const [tab,setTab]=useState("inicio"); const [toast,setToast]=useState<{text:string,error?:boolean}|null>(null); const [busy,setBusy]=useState(false); const [selected,setSelected]=useState<Item|null>(null); const [method,setMethod]=useState("pickup"); const [slotId,setSlotId]=useState(""); const [quantity,setQuantity]=useState(1); const [message,setMessage]=useState(""); const router=usePortalRouter();
  const load=useCallback(async()=>{ const response=await fetch("/api/portal?action=citizen"); if(response.status===401){router.replace("/entrar");return;} setData(await response.json()); },[router]);
  useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load]);
  async function act(action:string,payload:Record<string,unknown>={}) { setBusy(true); const response=await fetch("/api/portal",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})}); const result=await response.json() as {message?:string}; setBusy(false); setToast({text:result.message??(response.ok?"Tudo certo.":"Não foi possível continuar."),error:!response.ok}); setTimeout(()=>setToast(null),4500); if(response.ok) await load(); return response.ok; }
  async function logout(){await act("logout");router.replace("/");}
  const availableSlots=useMemo(()=>data?.slots.filter((slot)=>slot.method===method)??[],[data,method]);
  const unread=data?.notifications.filter((item)=>!item.read_at).length??0;
  if(!data)return <div className="loading"><div><div className="spinner"/>Carregando seu portal...</div></div>;
  const firstName=String(data.profile.full_name).split(" ")[0];
  return <div className="app-layout">
    <aside className="sidebar"><div className="brand"><span className="brand-mark">+</span><span>Saúde Perto de Você<small>Portal do Cidadão</small></span></div><nav className="nav">{nav.map((item)=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><span className="nav-symbol">{item.icon}</span>{item.label}{item.id==="mensagens"&&unread>0?` (${unread})`:""}</button>)}</nav><div className="sidebar-foot">Atendimento municipal seguro<br/><button className="btn btn-ghost btn-small" style={{color:"white",marginTop:10}} onClick={logout}>Sair</button></div></aside>
    <main className="app-main"><header className="app-header"><h2>{nav.find((item)=>item.id===tab)?.label}</h2><div className="user-chip"><div className="avatar">{firstName[0]}</div><div><strong>{data.profile.full_name}</strong><small className="muted" style={{display:"block"}}>{data.profile.cpf_masked}</small></div></div></header><div className="app-content">
      {(data.profile.validation_status!=="validated"||Number(data.profile.first_pickup_required)===1)&&<div className="banner"><span style={{fontSize:22}}>!</span><div><strong>Primeira retirada presencial</strong><div className="muted">Seus documentos precisam ser validados e a primeira retirada deve ser concluída presencialmente. Só depois a entrega em casa será liberada.</div></div></div>}
      {tab==="inicio"&&<>
        <div className="welcome"><div><h1>Olá, {firstName}!</h1><p className="muted">O que você precisa hoje?</p></div>{unread>0&&<button className="btn btn-secondary" onClick={()=>{setTab("mensagens");act("readNotifications");}}>{unread} aviso(s)</button>}</div>
        <div className="grid grid-3"><button className="card" style={{textAlign:"left",cursor:"pointer"}} onClick={()=>setTab("medicamentos")}><span className="quick-icon">Rx</span><h3>Solicitar medicamento</h3><p className="muted">Consulte o saldo e escolha um horário.</p></button><button className="card" style={{textAlign:"left",cursor:"pointer"}} onClick={()=>setTab("especialistas")}><span className="quick-icon">♡</span><h3>Consultar especialistas</h3><p className="muted">Veja as datas ou informe sua necessidade.</p></button><button className="card" style={{textAlign:"left",cursor:"pointer"}} onClick={()=>setTab("mensagens")}><span className="quick-icon">◌</span><h3>Falar com a farmácia</h3><p className="muted">Tire dúvidas sem precisar se deslocar.</p></button></div>
        <PushNotificationsCard/>
        <DocumentUpload busy={busy} onUpload={act}/>
        <ConsultationCards interests={data.interests} busy={busy} onConfirm={act} openSpecialties={()=>setTab("especialistas")}/>
        <section className="section"><div className="section-heading"><h2>Meus medicamentos</h2><button className="btn btn-secondary btn-small" onClick={()=>setTab("medicamentos")}>Nova solicitação</button></div><div className="grid grid-2">{data.requests.slice(0,4).map((request)=><article className="card" key={request.id}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><strong>{request.product_name}</strong><span className={`status status-${request.status}`}>{labels[String(request.status)]??request.status}</span></div><p className="medicine-meta" style={{marginTop:10}}>Protocolo {request.protocol}</p><p className="muted" style={{marginBottom:0}}>{request.method==="delivery"?"Entrega":"Retirada"} · {fmtDate(request.starts_at)}</p></article>)}{!data.requests.length&&<div className="card empty">Você ainda não fez solicitações.</div>}</div></section>
      </>}
      {tab==="medicamentos"&&<>
        <div className="section-heading"><div><h2>Medicamentos</h2><p className="muted">Escolha o medicamento. São poucos passos.</p></div></div>
        {!selected?<div className="grid grid-2">{data.products.map((product)=>{const available=Number(product.available);return <article className="card medicine-card" key={product.id}><div className="medicine-title"><div><h3>{product.name}</h3><span className="medicine-meta">{product.presentation}</span></div><span className={`stock ${available<=0?"stock-out":available<=Number(product.minimum_stock)?"stock-low":"stock-ok"}`}>{available<=0?"Sem estoque":available<=Number(product.minimum_stock)?"Estoque baixo":"Disponível"}</span></div>{available>0?<button className="btn btn-primary btn-block" onClick={()=>{setSelected(product);setMethod("pickup");setSlotId("");}}>Solicitar este medicamento</button>:<button disabled={data.needs.some((need)=>need.product_id===product.id)} className="btn btn-secondary btn-block" onClick={()=>act("needStock",{productId:product.id})}>{data.needs.some((need)=>need.product_id===product.id)?"Aviso já solicitado":"Avise-me quando chegar"}</button>}</article>})}</div>:<div className="panel"><div className="panel-head"><div><span className="eyebrow" style={{color:"var(--green)"}}>Nova solicitação</span><h3>{selected.name}</h3></div><button className="btn btn-ghost btn-small" onClick={()=>setSelected(null)}>Cancelar</button></div><div className="panel-body narrow">
          <div className="flow-steps"><span className="flow-step done">1</span><span className="flow-line done"/><span className="flow-step active">2</span><span className="flow-line"/><span className="flow-step">3</span></div>
          <div className="field"><label>Como quer receber?</label><div className="grid grid-2"><button className={`card ${method==="pickup"?"alert-success":""}`} style={{cursor:"pointer",textAlign:"left"}} onClick={()=>{setMethod("pickup");setSlotId("");}}><strong>Retirar na farmácia</strong><small className="muted" style={{display:"block",marginTop:5}}>Horários de 15 minutos, sem fila.</small></button><button disabled={data.profile.validation_status!=="validated"||Number(data.profile.first_pickup_required)===1||!selected.delivery_allowed} className={`card ${method==="delivery"?"alert-success":""}`} style={{cursor:"pointer",textAlign:"left"}} onClick={()=>{setMethod("delivery");setSlotId("");}}><strong>Receber em casa</strong><small className="muted" style={{display:"block",marginTop:5}}>Faixas de 1 hora, com 24h de antecedência.</small></button></div></div>
          <div className="field" style={{marginTop:20}}><label>Quantidade</label><input type="number" min="1" max={Number(selected.available)} value={quantity} onChange={(event)=>setQuantity(Number(event.target.value))}/></div>
          <div className="field" style={{marginTop:20}}><label>Escolha um horário</label><div className="slot-grid">{availableSlots.slice(0,24).map((slot)=><button key={slot.id} className={`slot ${slotId===slot.id?"active":""}`} onClick={()=>setSlotId(String(slot.id))}><strong>{new Date(String(slot.starts_at)).toLocaleDateString("pt-BR",{weekday:"short",day:"2-digit",month:"2-digit"})}</strong><small>{new Date(String(slot.starts_at)).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}–{new Date(String(slot.ends_at)).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})} · {Number(slot.capacity)-Number(slot.reserved_count)} vaga(s)</small></button>)}</div></div>
          <div className="field" style={{marginTop:20}}><label htmlFor="prescription">Receita {selected.requires_prescription?"(obrigatória)":"(se houver)"}</label><input id="prescription" type="file" accept="application/pdf,image/jpeg,image/png" required={Boolean(selected.requires_prescription)} /><span className="hint">PDF, JPG ou PNG, até 5 MB. A receita será conferida pela farmácia.</span></div>
          <div className="alert">O saldo exibido não garante a dispensação. A farmácia conferirá cadastro, receita, quantidade e lote antes de aprovar.</div>
          <button className="btn btn-primary btn-block" disabled={!slotId||busy} style={{marginTop:22}} onClick={async()=>{const input=document.querySelector<HTMLInputElement>("#prescription");const file=input?.files?.[0];if(selected.requires_prescription&&!file){setToast({text:"Envie a receita para continuar.",error:true});return;}let prescriptionBase64:string|null=null;if(file){if(file.size>5*1024*1024){setToast({text:"A receita deve ter no máximo 5 MB.",error:true});return;}prescriptionBase64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});}if(await act("requestMedication",{productId:selected.id,quantity,method,slotId,prescriptionName:file?.name??null,prescriptionType:file?.type??null,prescriptionBase64}))setSelected(null);}}>Confirmar solicitação</button>
        </div></div>}
      </>}
      {tab==="especialistas"&&<>
        <div className="section-heading"><div><h2>Consultar especialidades</h2><p className="muted">Veja quem vem atender e informe somente sua intenção de consulta.</p></div></div><div className="alert">Registrar interesse não é encaminhamento, regulação nem consulta agendada. Em urgência, procure imediatamente o serviço de saúde indicado pelo município.</div>
        <ConsultationCards interests={data.interests} busy={busy} onConfirm={act}/>
        {data.schedules.length>0&&<><h3>Outras datas no município</h3><div className="grid grid-2" style={{marginBottom:22}}>{data.schedules.map((schedule)=><article className="card" key={schedule.id}><span className={`status status-${schedule.status}`}>{labels[String(schedule.status)]??schedule.status}</span><h3 style={{marginTop:13}}>{schedule.specialty_name}</h3><p className="muted">{fmtDate(schedule.starts_at)}<br/><strong>{schedule.location_name}</strong><br/>{schedule.location_address}</p></article>)}</div></>}
        <div className="grid grid-2">{data.specialties.map((specialty)=>{const registered=data.interests.some((interest)=>interest.specialty_id===specialty.id&&interest.status!=="cancelled");return <article className="card" key={specialty.id}><h3>{specialty.name}</h3><p className="muted">{specialty.description}</p><p className="medicine-meta">{specialty.demand} pessoa(s) já informaram necessidade.</p><button className="btn btn-secondary btn-block" disabled={registered||busy} onClick={()=>act("specialtyInterest",{specialtyId:specialty.id,location:data.profile.district??"Município",period:"qualquer"})}>{registered?"Necessidade registrada":"Tenho interesse nesta consulta"}</button></article>})}</div>
      </>}
      {tab==="mensagens"&&<div className="grid grid-2"><section className="panel"><div className="panel-head"><h3>Fale com a farmácia</h3></div><div className="chat">{data.messages.map((item)=><div key={item.id} className={`bubble ${item.sender==="citizen"?"mine":"theirs"}`}>{item.body}<small>{fmtDate(item.created_at)}</small></div>)}{!data.messages.length&&<div className="empty">Envie uma mensagem. A equipe responderá por aqui.</div>}</div><form className="chat-compose" onSubmit={async(event:FormEvent)=>{event.preventDefault();if(await act("sendMessage",{message}))setMessage("");}}><input aria-label="Mensagem" placeholder="Escreva sua dúvida..." value={message} onChange={(event)=>setMessage(event.target.value)}/><button className="btn btn-primary" disabled={!message.trim()||busy}>Enviar</button></form></section><section><div className="panel"><div className="panel-head"><h3>Avisos</h3><button className="btn btn-ghost btn-small" onClick={()=>act("readNotifications")}>Marcar como lidos</button></div><div className="panel-body form-grid">{data.notifications.map((item)=><article key={item.id} style={{paddingBottom:13,borderBottom:"1px solid var(--line)"}}><strong>{item.title}</strong><p className="muted" style={{margin:"5px 0"}}>{item.message}</p><small className="medicine-meta">{fmtDate(item.created_at)}</small></article>)}{!data.notifications.length&&<div className="empty">Nenhum aviso por enquanto.</div>}</div></div></section></div>}
      {tab==="privacidade"&&<PrivacyPanel requests={data.privacyRequests??[]} busy={busy} onSubmit={act}/>}
    </div></main>
    <nav className="mobile-nav">{nav.map((item)=><button key={item.id} className={tab===item.id?"active":""} onClick={()=>setTab(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav>
    {toast&&<div role="status" className={`toast ${toast.error?"error":""}`}>{toast.text}</div>}
  </div>;
}

function DocumentUpload({busy,onUpload}:{busy:boolean;onUpload:(action:string,payload:Record<string,unknown>)=>Promise<boolean>}){const[file,setFile]=useState<File|null>(null);async function send(){if(!file||file.size>5*1024*1024)return;const base64=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(",")[1]??"");reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file);});if(await onUpload("uploadDocument",{fileName:file.name,contentType:file.type,base64}))setFile(null);}return <section className="panel section"><div className="panel-head"><div><h3>Meus documentos</h3><span className="medicine-meta">Envie RG, CPF ou comprovante para adiantar a conferência.</span></div></div><div className="panel-body"><div className="field"><label htmlFor="citizen-document">Documento (PDF, JPG ou PNG, até 5 MB)</label><input id="citizen-document" type="file" accept="application/pdf,image/jpeg,image/png" onChange={(event)=>setFile(event.target.files?.[0]??null)}/></div>{file&&file.size>5*1024*1024&&<div className="alert alert-error">O arquivo ultrapassa 5 MB.</div>}<button className="btn btn-secondary" disabled={!file||file.size>5*1024*1024||busy} style={{marginTop:12}} onClick={send}>Enviar documento</button></div></section>}

function PrivacyPanel({requests,busy,onSubmit}:{requests:Item[];busy:boolean;onSubmit:(action:string,payload:Record<string,unknown>)=>Promise<boolean>}){return <><div className="section-heading"><div><h2>Privacidade e seus dados</h2><p className="muted">O município é o controlador dos dados. A ferramenta trata somente as informações necessárias para executar o serviço público de saúde.</p></div></div><div className="grid grid-2"><section className="panel"><div className="panel-head"><h3>Solicitar atendimento</h3></div><form className="panel-body form-grid" onSubmit={async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=event.currentTarget;if(await onSubmit("privacyRequest",Object.fromEntries(new FormData(form))))form.reset();}}><div className="field"><label>O que você precisa?</label><select name="requestType" required><option value="access">Acesso aos meus dados</option><option value="correction">Correção de cadastro</option><option value="information">Informações sobre uso dos dados</option><option value="review">Revisão de uma decisão</option></select></div><div className="field"><label>Detalhes</label><textarea name="details" maxLength={1500} rows={5} placeholder="Explique sua solicitação de forma simples."/></div><button className="btn btn-primary" disabled={busy}>Registrar solicitação</button><small className="muted">A exclusão pode não ser aplicável quando houver obrigação legal de guarda. Cada pedido será analisado pela prefeitura.</small></form></section><section className="panel"><div className="panel-head"><h3>Meus pedidos</h3></div><div className="panel-body form-grid">{requests.map((item)=><div key={item.id}><strong>{String(item.request_type)==="access"?"Acesso aos dados":String(item.request_type)==="correction"?"Correção de cadastro":String(item.request_type)==="information"?"Informações":"Revisão"}</strong><div className="medicine-meta">{fmtDate(item.created_at)} · {item.status==="open"?"Recebido":item.status==="in_review"?"Em análise":item.status==="answered"?"Respondido":"Encerrado"}</div></div>)}{!requests.length&&<div className="empty">Nenhuma solicitação registrada.</div>}</div></section></div><section className="panel section"><div className="panel-body"><h3>Como protegemos suas informações</h3><p className="muted">CPF não é exibido por completo; senhas e códigos são armazenados de forma protegida; acessos administrativos usam perfis; ações relevantes ficam em trilha de auditoria; documentos são aceitos somente em formatos controlados. O contato do encarregado e os prazos oficiais devem ser definidos pelo município antes da implantação.</p></div></section></>}
function ConsultationCards({interests,busy,onConfirm,openSpecialties}:{interests:Item[];busy:boolean;onConfirm:(action:string,payload:Record<string,unknown>)=>Promise<boolean>;openSpecialties?:()=>void}){const scheduled=interests.filter((item)=>item.schedule_id&&["notified","confirmed"].includes(String(item.status)));return <section className="section"><div className="section-heading"><div><h2>Minhas consultas</h2><p className="muted">Pendentes de confirmação e já confirmadas.</p></div>{openSpecialties&&<button className="btn btn-secondary btn-small" onClick={openSpecialties}>Ver especialidades</button>}</div><div className="grid grid-2">{scheduled.map((item)=><article className="card" key={item.id}><div style={{display:"flex",justifyContent:"space-between",gap:10}}><h3>{item.specialty_name}</h3><span className={`status ${item.status==="confirmed"?"status-approved":"status-received"}`}>{item.status==="confirmed"?"Confirmada":"Confirmar presença"}</span></div><p className="muted"><strong>{fmtDate(item.starts_at)}</strong><br/>{item.location_name}<br/>{item.location_address}{item.location_reference&&<><br/>Referência: {item.location_reference}</>}</p>{item.status==="notified"&&<button className="btn btn-primary btn-block" disabled={busy} onClick={()=>onConfirm("confirmConsultation",{interestId:item.id})}>Confirmar minha presença</button>}{item.status==="confirmed"&&<div className="alert alert-success">Sua presença está confirmada. Chegue 15 minutos antes.</div>}</article>)}{!scheduled.length&&<div className="card empty">Nenhuma consulta vinculada ao seu cadastro no momento.</div>}</div></section>}
